# K-近邻算法 

##    * Python导入数据，实施KNN算法

In [6]:

import operator
from numpy import *

In [7]:
group,labels = kNN.createDataset()

NameError: name 'kNN' is not defined

In [ ]:
group

## 实施KNN算法 

In [8]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()     
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    return sortedClassCount[0][0]

## 2.2.1 从文本文件中解析数据

In [9]:

filename = 'datingTestSet.txt'
fr =open(filename)
arrayOline = fr.readlines()
numberOflines  = len(arrayOline)
returnMat = zeros((numberOflines,3))
classLabelVector = []
index = 0
for line in arrayOline:
    line = line.strip()
    listFromLine = line.split('\t')
    returnMat[index,:] = listFromLine[0:3]
    classLabelVector.append(listFromLine[-1])
    index+=1


In [ ]:
import operator

In [10]:
Int = {'largeDoses':3,'smallDoses':2,'didntLike':1}
def file2matrix(filename):
    fr = open(filename)
    numberOfLines = len(fr.readlines())         #get the number of lines in the file
    returnMat = zeros((numberOfLines,3))        #prepare matrix to return
    classLabelVector = []                       #prepare labels return   
    fr = open(filename)
    index = 0
    for line in fr.readlines():
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        classLabelVector.append(Int[listFromLine[-1]])
        index += 1
    return returnMat,classLabelVector


In [11]:
datingDatMat,datingLabels = file2matrix('datingTestSet.txt')

## 2.2.2 分析数据：使用Matlibplot创建散点图

In [ ]:
import matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(datingDatMat[:,0],datingDatMat[:,2],15.0*array(datingLabels),15.0*array(datingLabels))
plt.show()

## 2.2.3 归一化数值

In [12]:
def file2matrix(filename):
    fr = open(filename)
    numberOfLines = len(fr.readlines())         #get the number of lines in the file
    returnMat = zeros((numberOfLines,3))        #prepare matrix to return
    classLabelVector = []                       #prepare labels return   
    fr = open(filename)
    index = 0
    for line in fr.readlines():
        line = line.strip()
        listFromLine = line.split('\t')
        returnMat[index,:] = listFromLine[0:3]
        classLabelVector.append(Int[listFromLine[-1]])
        index += 1
    return returnMat,classLabelVector

def autoNorm(dataSet):
    minvals = dataSet.min(0)
    maxvals = dataSet.max(0)
    ranges = maxvals - minvals
    normDataSet = zeros(shape(dataSet))
    m =  dataSet.shape[0]
    normDataSet = dataSet - tile(minvals,(m,1))
    normDataSet = normDataSet/tile(ranges, (m,1))
    return normDataSet , ranges,minvals
datingDateMat, datingLabels = file2matrix("datingTestSet.txt")
normMat,ranges ,minvals = autoNorm(datingDatMat)

##  2.2.4 测试算法：作为完整程序验证分类器

In [13]:
from DolphinML.KNN import Knn

In [15]:
k = Knn(topK=4)
k.train

In [18]:
datingDateMat, datingLabels = file2matrix("datingTestSet.txt")
normMat,ranges ,minvals = autoNorm(datingDatMat)

In [20]:
normMat.shape

(1000, 3)

In [21]:
datingDatMat.shape

(1000, 3)

In [28]:
normMat[:10]

array([[ 0.44832535,  0.39805139,  0.56233353],
       [ 0.15873259,  0.34195467,  0.98724416],
       [ 0.28542943,  0.06892523,  0.47449629],
       [ 0.82320073,  0.62848007,  0.25248929],
       [ 0.42010233,  0.07982027,  0.0785783 ],
       [ 0.79972171,  0.48480189,  0.60896055],
       [ 0.39385141,  0.32652986,  0.71533516],
       [ 0.46745478,  0.63464542,  0.32031191],
       [ 0.73950675,  0.41261212,  0.44153637],
       [ 0.38875681,  0.58668982,  0.88936006]])

In [34]:
k.train(normMat[:700],datingLabels[:700])

In [35]:
k.predict(normMat[700:])

TypeError: only integer arrays with one element can be converted to an index

In [29]:
def datingClassTest():
    hoRatio = 0.10
    datingDateMat, datingLabels = file2matrix("datingTestSet.txt")
    normMat,ranges ,minvals = autoNorm(datingDatMat)
    m = normMat.shape[0]
    numTestVecs = int(m*hoRatio)
    errorcount = 0.0
    k = Knn(topK=4)
    k.train(normMat[:700],datingLabels[:700])
    s = k.predict(normMat[700:])
    
    return s
#     for i in range(numTestVecs):
#         classifierResult = classify0(normMat[i,:],normMat[numTestVecs:m],datingLabels[numTestVecs:m],4)
        
#         if classifierResult != datingLabels[i]:
#             errorcount += 1.0
#             print("come_back: %d, the real result is %d "%(classifierResult,datingLabels[i]))
#     print("the error rate:%f"%(errorcount/numTestVecs))
        
datingClassTest()

TypeError: only integer arrays with one element can be converted to an index

In [44]:
def datingClassTest():
    hoRatio = 0.30
    datingDateMat, datingLabels = file2matrix("datingTestSet.txt")
    normMat,ranges ,minvals = autoNorm(datingDatMat)
    m = normMat.shape[0]
    numTestVecs = int(m*hoRatio)
    errorcount = 0.0
    print(normMat)
    box=[]
    for i in range(numTestVecs):
        classifierResult = classify0(normMat[i,:],normMat[numTestVecs:],datingLabels[numTestVecs:],4)
        box.append(classifierResult)
        if classifierResult != datingLabels[i]:
            errorcount += 1.0
            print("come_back: %d, the real result is %d "%(classifierResult,datingLabels[i]))
    print("the error rate:%f"%(errorcount/numTestVecs))
    return box
        
ret = datingClassTest()

[[ 0.44832535  0.39805139  0.56233353]
 [ 0.15873259  0.34195467  0.98724416]
 [ 0.28542943  0.06892523  0.47449629]
 ..., 
 [ 0.29115949  0.50910294  0.51079493]
 [ 0.52711097  0.43665451  0.4290048 ]
 [ 0.47940793  0.3768091   0.78571804]]
come_back: 2, the real result is 3 
come_back: 3, the real result is 1 
come_back: 2, the real result is 3 
come_back: 2, the real result is 1 
come_back: 3, the real result is 1 
come_back: 2, the real result is 3 
come_back: 1, the real result is 3 
come_back: 2, the real result is 3 
come_back: 3, the real result is 1 
come_back: 3, the real result is 1 
come_back: 3, the real result is 1 
come_back: 2, the real result is 1 
come_back: 2, the real result is 3 
come_back: 2, the real result is 3 
come_back: 2, the real result is 1 
come_back: 3, the real result is 2 
come_back: 3, the real result is 1 
come_back: 3, the real result is 2 
come_back: 2, the real result is 3 
come_back: 2, the real result is 1 
the error rate:0.066667


In [45]:
sum(ret)

601

In [46]:
len(ret)

300

##  2.2.5 使用算法：构建完整可用系统

In [23]:
def classifyPerson():
    result = ['not at all','in small doses','in large doses']
    percentTats = float(input("video games?"))
    ffmiles = float(input('flier mailes earned per year?'))
    icecream = float(input('icecream per year?'))
    datingDataMat,datingLabels = file2matrix('datingTestSet2.txt')
    normmat,ranges,minvals = autoNorm(datingDatMat)
    inArr = array([ffmiles,percentTats,icecream])
    testvec = (inArr-minvals)/ranges
    classifierResult = classify0(testvec,normmat,datingLabels,3)
    print('you will probably like this person:',result[classifierResult-1])

In [24]:
classifyPerson()

KeyboardInterrupt: 