In [1]:
c = [0,1,2,3,4,5,6,7,8,9]
print(c[:5])

[0, 1, 2, 3, 4]


In [2]:
print(c[6:])

[6, 7, 8, 9]


In [1]:
from numpy import *


In [25]:
randMat = mat([[[23,2,5,6],[11,12,14,16]],[[55,36,5,89],[47,12,34,10]]])
randMat

ValueError: matrix must be 2-dimensional

In [20]:
randMat.min(0)

matrix([[11,  2,  5,  6]])

In [49]:
d ={1:'23','er':'wers','wsx':'sss'}

In [50]:
d.

dict_items([(1, '23'), ('er', 'wers'), ('wsx', 'sss')])

In [36]:
randAry2 = array([[23,2,5,6],[11,12,14,16]])
randAry2

array([[23,  2,  5,  6],
       [11, 12, 14, 16]])

In [43]:
randAry3 = array([[[23,2],[11,12]],[[5,89],[4,10]]])
randAry3

array([[[23,  2],
        [11, 12]],

       [[ 5, 89],
        [ 4, 10]]])

In [47]:
print(randAry2.min(0));print("=======");print(randAry3.min(2));

[11  2  5  6]
[[ 2 11]
 [ 5  4]]


In [27]:
randAry

array([[[23,  2,  5,  6],
        [11, 12, 14, 16]],

       [[55, 36,  5, 89],
        [47, 12, 34, 10]]])

In [32]:
info(randAry.min)

a.min(axis=None, out=None, keepdims=False)

Return the minimum along a given axis.

Refer to `numpy.amin` for full documentation.

See Also
--------
numpy.amin : equivalent function


In [5]:
s='01010011010'
type(int(s))

int